# Generated by Django 5.2 on 2025-07-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculadoraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('maestro', 'Maestro')], default='alumno', max_length=10),
        ),
    ]
