# Generated by Django 5.2 on 2025-07-03 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField(verbose_name='Enunciado de la pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('true_false', 'Verdadero o Falso')], default='multiple_choice', max_length=20, verbose_name='Tipo de pregunta')),
                ('respuesta_correcta_tf', models.BooleanField(blank=True, help_text='Solo para preguntas de Verdadero o Falso. Marcar si la afirmación es Verdadera.', null=True, verbose_name='Respuesta Correcta (Verdadero/Falso)')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=255, verbose_name='Texto de la opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es la respuesta correcta?')),
                ('pregunta', models.ForeignKey(limit_choices_to={'tipo_pregunta': 'multiple_choice'}, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='preguntas.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'unique_together': {('pregunta', 'texto_opcion')},
            },
        ),
    ]
