# Generated by Django 5.2 on 2025-07-29 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='opcion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta_correcta_tf',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta_correcta_vf',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='es_correcta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='preguntas.pregunta'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='texto_opcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto_pregunta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('VF', 'Verdadero/Falso'), ('OM', 'Opción Múltiple')], max_length=2),
        ),
    ]
